repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        stages: [commit]
      - id: debug-statements
        stages: [commit]
